n = int(input('Digite um número: '))
t = [1*n, 2*n, 3*n, 4*n, 5*n, 6*n, 7*n, 8*n, 9*n, 10*n]
print('O número digitado foi {}.'.format(n))
print('=' * 15)
print('TABUADA do {}: '.format(n))
print('{} x {:2} = {}'.format(n, 1, t[0]))
print('{} x {:2} = {}'.format(n, 2, t[1]))
print('{} x {:2} = {}'.format(n, 3, t[2]))
print('{} x {:2} = {}'.format(n, 4, t[3]))
print('{} x {:2} = {}'.format(n, 5, t[4]))
print('{} x {:2} = {}'.format(n, 6, t[5]))
print('{} x {:2} = {}'.format(n, 7, t[6]))
print('{} x {:2} = {}'.format(n, 8, t[7]))
print('{} x {:2} = {}'.format(n, 9, t[8]))
print('{} x {:2} = {}'.format(n, 10, t[9]))
print('=' * 15)
